# pyproject.toml

[tool.isort]
profile = "black"
src_paths = ["app.py", "core", "paginas", "tests"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip_glob = ["*/.venv/*", "*/__pycache__/*"]

[tool.black]
line-length = 88
exclude = '''
/(
    \.venv
  | __pycache__
)/
'''

[tool.flake8]
max-line-length = 88
extend-ignore = "E203, E501, W503"
exclude = [
    ".venv",
    "__pycache__",
]
