name: CI/CD - Streamlit App

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    # --- JOB DE INTEGRAÇÃO CONTÍNUA (TESTES) ---
   ci-testes:
    name: Build e Testes
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configurar o ambiente Python
      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'

      # 3. Instalar as dependências do projeto
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Verificar a formatação com Black
      - name: Lint com Black
        run: | 
          black --check .

      # 5. Verificar a ordenação dos imports com isort
      - name: lint com isort
        run: |
          isort --check-only .

      # 6. Executar o 'linter' (flake8) para verificar a qualidade do código
      - name: lint com flake8
        run: |
          flake8 . --count --ignore=E203,E501,W503 --show-source --statistics

      # 7. Executar os testes com o pytest
      - name: Testes com o pytest
        run: |
          pytest

